/home/gbenato/Cuore/Analysis/BATGraphHistoFit/bin/CombineEfficiency \
    --input-path /home/gbenato/Cuore/Data/TAUP23/ACEfficiency_M/ \
    --input-file eff.root \
    --input-histo eff_1461 \
    --input-path /home/gbenato/Cuore/Data/TAUP23/PCAEfficiency_P/ \
    --input-file output_eff.root \
    --input-histo h1_fit_observable_fQ \
    --input-path /home/gbenato/Cuore/Data/TAUP23/PulserEfficiency/ \
    --input-ascii-file PulserEfficiencyAsOne \
    --first-dataset 3817 \
    --last-dataset 3818 \
    --output-path /home/gbenato/Cuore/Data/TAUP23
